FROM bcit/alpine:3.10 as build

RUN apk add --no-cache \
		ca-certificates \
		gcc \
		gettext \
		make \
		musl-dev \
		openssl-dev \
        binutils \
        file \
        gmp \
        isl \
        libatomic \
        libgcc \
        libgomp \
        libintl \
        libmagic \
        libunistring \
        libxml2 \
        mpc1 \
        mpfr3 \
        ncurses-libs \
        ncurses-terminfo \
        ncurses-terminfo-base \
        openssl \
        pkgconf \
        zlib-dev

WORKDIR /tmp
RUN wget https://www.stunnel.org/downloads/stunnel-<%= image.labels['stunnel_version'] %>.tar.gz \
 && tar -zxvf stunnel-<%= image.labels['stunnel_version'] %>.tar.gz

WORKDIR /tmp/stunnel-<%= image.labels['stunnel_version'] %>
RUN ./configure \
 && make \
 && cp src/stunnel /usr/local/bin/stunnel

WORKDIR /

FROM bcit/alpine:3.10
<%= snippet('labels', binding) -%>

RUN apk add --no-cache \
        ca-certificates \
        gettext \
 && mkdir \
    /etc/stunnel \
    /var/run/stunnel \
    /var/log/stunnel \
 && chmod -R g+rw \
    /etc/stunnel \
    /var/run/stunnel \
    /var/log/stunnel \
    /usr/local/share/ca-certificates \
    /etc/ssl

COPY 60-stunnel-config.sh /docker-entrypoint.d/
COPY openssl.cnf /etc/stunnel/
COPY stunnel.conf.template /etc/stunnel/
COPY --from=build /usr/local/bin/stunnel /usr/local/bin/stunnel

ENV STUNNEL_CACERT "/etc/stunnel/stunnel-ca.crt"
ENV STUNNEL_CLIENT no
ENV STUNNEL_CONF /etc/stunnel/stunnel.conf
ENV STUNNEL_CONF_TEMPLATE /etc/stunnel/stunnel.conf.template
ENV STUNNEL_CERT /etc/stunnel/stunnel.pem
ENV STUNNEL_DEBUG 6
ENV STUNNEL_KEY  /etc/stunnel/stunnel.key
ENV STUNNEL_VERIFY_CHAIN no
ENV RANDOM_SOURCE /dev/urandom

CMD [ "sh", "-c", "/usr/local/bin/stunnel $STUNNEL_CONF" ]
